Release 0.0.1
OwlByTech/optitech-web pull request #20
Opened 2024-07-16 14:38 UTC by JosephSC0121

2024-07-20 02:49 UTC, Camilo-Camargo approved these changes

2024-07-20 16:02 UTC, CamiloArias12 approved these changes

2024-08-12 14:44 UTC, Camilo-Camargo requested changes

2024-08-12 14:44 UTC, Camilo-Camargo commented on .env.example
se cambio a https://github.com/OwlByTech/optitech-web/pull/38

2024-08-12 14:44 UTC, Camilo-Camargo commented
se cambio a https://github.com/OwlByTech/optitech-web/pull/38

2024-08-12 14:44 UTC, closed without merging