add page principal
OwlByTech/optitech-web pull request #3
Opened 2024-06-18 20:48 UTC by Alejandro-Suarez-Rincon

# Añadir pagina principal
## Description
Este pr es para la pagina principal que redirecciona a registro e iniciar sesion.
![imagen](https://github.com/OwlByTech/optitech-web/assets/126360945/7aa43579-3252-423c-9376-3fdd89d9fcb4)

## Checklist:
- [x]  My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-18 20:52 UTC, Camilo-Camargo commented on src/app/principal/page.tsx
> +  title: "Opti Tech",
```suggestion
  title: "OptiTech",
```

2024-06-18 20:52 UTC, Camilo-Camargo commented on src/auth.config.ts
> +                return true
por que agregamos esto?

2024-06-18 20:52 UTC, Camilo-Camargo commented on src/auth.config.ts
> +                return true
creo que si necesitamos mas rutas se podria iterar el enum de `ROUTES_AUTH`

2024-06-18 20:54 UTC, Alejandro-Suarez-Rincon commented on src/auth.config.ts
> +                return true
si no se agrega no cargan las pantallas, todas se pasan automáticamente a otra

2024-06-18 21:14 UTC, Alejandro-Suarez-Rincon commented on src/auth.config.ts
> +                return true
https://github.com/OwlByTech/optitech-web/pull/3/commits/fa3613106958793c2f324e8fb5ce488eedc4e345

2024-06-19 14:52 UTC, CamiloArias12 requested changes

2024-06-19 14:52 UTC, CamiloArias12 commented on src/modules/auth/templates/principal.tsx
Es mejor utilizar link de nextjs
https://nextjs.org/docs/pages/api-reference/components/link

2024-06-19 15:23 UTC, Alejandro-Suarez-Rincon commented on src/modules/auth/templates/principal.tsx
solucionado https://github.com/OwlByTech/optitech-web/pull/3/commits/2d5c021f8b2d73740842e8589b8ad7d6b608c8e5

2024-06-19 17:17 UTC, JosephSC0121 commented on src/modules/auth/templates/principal.tsx
> +          <p>Welcome back</p>
Comentado en el otro pr

2024-06-19 17:18 UTC, JosephSC0121 commented on src/modules/auth/types/auth.ts
> +    PRINCIPAL = "/principal",
@developers-owlbytech dejar las rutas en español?

2024-06-19 17:19 UTC, JosephSC0121 approved these changes
Lo mismo del format, muchas de las cosas que opino deberían cambiar, las comenté en el otro PR

2024-06-20 14:10 UTC, Alejandro-Suarez-Rincon commented on src/modules/auth/templates/principal.tsx
> +          <p>Welcome back</p>
https://github.com/OwlByTech/optitech-web/pull/3/commits/3754d10bd726a07cec6106b32464679407e2e0b9

2024-06-20 14:11 UTC, Alejandro-Suarez-Rincon commented on src/modules/auth/types/auth.ts
> +    PRINCIPAL = "/principal",
como se esta programando en inglés por eso las deje asi

2024-06-20 15:44 UTC, Camilo-Camargo approved these changes

2024-06-20 17:40 UTC, JosephSC0121 commented on src/modules/auth/types/auth.ts
> +    PRINCIPAL = "/principal",
Entonces sería más apropiado main, no?

2024-06-21 14:04 UTC, CamiloArias12 approved these changes

2024-06-21 14:07 UTC, merged