pagina del paso 3
OwlByTech/optitech-web pull request #5
Opened 2024-06-19 17:09 UTC by Alejandro-Suarez-Rincon

# Añadir pagina principal
## Description
Este pr es para la pagina del paso 3 solo es el componente, este no es visible hasta no ser llamado.

![Captura desde 2024-06-19 12-05-18](https://github.com/OwlByTech/optitech-web/assets/126360945/54dd4638-b522-4ca4-9484-4cd407f4567f)

![Captura desde 2024-06-19 12-04-50](https://github.com/OwlByTech/optitech-web/assets/126360945/ec7dd217-8040-4ed8-a558-bf25987451fa)

## Checklist:

- [x]  My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-20 16:35 UTC, Camilo-Camargo commented on src/modules/common/components/button/index.tsx
> +  // Combina las clases Tailwind con las clases predeterminadas de NextUI
```suggestion
```

2024-06-21 04:02 UTC, CamiloArias12 requested changes

2024-06-21 04:02 UTC, CamiloArias12 commented on src/modules/common/components/button/index.tsx
> +    >
```suggestion
  return (
    <ButtonNext
      className={`text-white bg-black ${className}`}
      radius="none"
      type={type}
      {...props}
    >
```

2024-06-21 13:31 UTC, Camilo-Camargo approved these changes

2024-06-21 14:36 UTC, CamiloArias12 approved these changes

2024-06-21 14:37 UTC, merged